modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/StructureVisualizer"
license="MIT"

[[mods]]
modId="structurevisualizer"
version="${file.jarVersion}"
displayName="Structure Visualizer"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-visualizer"
authors="Mrbysco, ShyNieke"
description='''
Ah, so this is where I place that block
'''
[[dependencies.structurevisualizer]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="CLIENT"